backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/', include(('core.urls', 'core'), namespace='admin')),

    path('', include('core.urls')),

  
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from backend import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),
    path('login/', auth_views.LoginView.as_view(), name='login'),

    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('contact/', views.contact, name='contact'),
    path('events/', views.announcements, name='events'),
    path('calendars/', views.my_calendars, name='my_calendars'),
    path('grades/', views.my_grades, name='grades'),
   
    path('assign-grades/<int:classroom_id>/change/', views.assign_grades, name='assign-grades'),
    path('homework_assignment/', views.homework_assignment, name='homework_assignment'),
    path('homework_submission/', views.student_homeworks, name='homework_submission'),
    path('view_submissions/', views.view_submissions, name='view_submissions'),
    path('view_absences/', views.parents_absences_view, name='view_absences'),
    path('view_children_grades/', views.get_grades_parents, name='view_children_grades'),
    path('view_student_grades', views.get_grades_student, name='view_student_grades'),
    path('student_calendar/', views.view_schedule_student,name='student_calendar'),
    path('parent_calendar/', views.view_schedule_parent,name='parent_calendar'),
    path('teacher_courses/', views.teacher_courses, name='teacher_courses'),
    path('courses/', views.view_courses, name='Courses'),
    path('my_student_courses/', views.student_courses, name='my_student_courses'),
    path('teacher_remarks/', views.teacher_remarks, name='teacher_remarks'),
    path('parent_remarks/', views.parent_remarks, name="parent_remarks")


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from datetime import date, timezone
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.hashers import make_password
from django.forms import ValidationError



class CustomUser(AbstractUser):
    
    USER_TYPE_CHOICES = (
        ('teacher', 'Teacher'),
        ('student', 'Student'),
        ('parent', 'Parent'),
        ('admin/staff', 'Admin/Staff')
    )

    user_type = models.CharField(max_length=30, choices=USER_TYPE_CHOICES)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    date_of_birth = models.DateField(blank=True, null=True)

    def save(self, *args, **kwargs):
        #so i don't double hash password and i do hash password on password change
        # Check if the user already exists
        if self.pk:
            orig = CustomUser.objects.get(pk=self.pk)
            if orig.password != self.password:  # The password has been changed
                self.password = make_password(self.password)
        else:  # This is a new user
            self.password = make_password(self.password)
            super().save(*args, **kwargs)  # Save the user first, because the user needs to exist before creating the related instance

            # Create the associated Teacher, Student, or Parent instance if it doesn't already exist
            if self.user_type == 'teacher' and not hasattr(self, 'teacher'):
                Teacher.objects.create(user=self)
            elif self.user_type == 'student' and not hasattr(self, 'student'):
                Student.objects.create(user=self)
            elif self.user_type == 'parent' and not hasattr(self, 'parent'):
                Parent.objects.create(user=self)
            return

        super().save(*args, **kwargs)

class Teacher(models.Model):
    user= models.OneToOneField(CustomUser,on_delete=models.CASCADE,related_name='teacher')
    class Meta:
        verbose_name = 'Teacher'
        verbose_name_plural = 'Teachers'
    def __str__(self):
        return self.user.username
         
class Student(models.Model):
    user= models.OneToOneField(CustomUser,on_delete=models.CASCADE,related_name='student')
    classroom= models.ForeignKey('Classroom',on_delete=models.SET_NULL,related_name='student',null=True, blank=True)
    parent=models.ForeignKey('Parent',on_delete=models.SET_NULL,related_name='children',null=True,blank=True)
    matricule=models.CharField(max_length=30,null=True,blank=True)
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )   
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    class Meta:
        verbose_name = 'Student'
        verbose_name_plural = 'Students'
    def __str__(self):
        return self.user.username
    @property
    def age(self):
        if self.user.date_of_birth:
            return date.today().year - self.user.date_of_birth.year - ((date.today().month, date.today().day) < (self.user.date_of_birth.month, self.user.date_of_birth.day))
        else:
            return None


class Parent(models.Model):
    user= models.OneToOneField(CustomUser,on_delete=models.CASCADE,related_name='parent')
    class Meta:
        verbose_name = 'Parent'
        verbose_name_plural = 'Parents'
    def __str__(self):
        return self.user.username
    
    
TRIMESTER_CHOICES = (
        (1, 'First Trimester'),
        (2, 'Second Trimester'),
        (3, 'Third Trimester'),
    )
        
class Subject(models.Model):
    name = models.CharField(max_length=255)
    coefficient = models.IntegerField()
    teachers=models.ManyToManyField(Teacher, related_name='subjects', blank=True)


    def __str__(self):
        return self.name


class TimeSlot(models.Model):
    DAY_CHOICES = [
        ('SAT', 'Saturday'),
        ('SUN', 'Sunday'),
        ('MON', 'Monday'),
        ('TUE', 'Tuesday'),
        ('WED', 'Wednesday'),
        ('THU', 'Thursday'),
        ('FRI', 'Friday'),

    ]
    TIME_RANGES = [
    ('7:00 - 8:00', '7:00 - 8:00'),
    ('8:00 - 9:00', '8:00 - 9:00'),
    ('9:00 - 10:00', '9:00 - 10:00'),
    ('10:00 - 11:00', '10:00 - 11:00'),
    ('11:00 - 12:00', '11:00 - 12:00'),
    ('12:00 - 1:00', '12:00 - 1:00'),
    ('1:00 - 2:00', '1:00 - 2:00'),
    ('2:00 - 3:00', '2:00 - 3:00'),
    ('3:00 - 4:00', '3:00 - 4:00'),
    ('4:00 - 5:00', '4:00 - 5:00'),
    ('5:00 - 6:00', '5:00 - 6:00'),


     ]

    day = models.CharField(max_length=3, choices=DAY_CHOICES)
    time_range= models.CharField(max_length=13, choices=TIME_RANGES, default='8:00 - 9:00', null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    subject= models.ForeignKey(Subject, on_delete=models.SET_NULL, related_name='timeslots', null=True, blank=True)
    calendar = models.ForeignKey('Calendars', on_delete=models.CASCADE, related_name='timeslots', null= True, blank=True)

    def __str__(self):
        return f'{self.get_day_display()}  {self.time_range}'

class Calendars(models.Model):
    title = models.CharField(max_length=255)
    CALENDAR_TYPES = [
        ('CLASS', 'Classroom Schedule'),
        ('CAFE', 'Cafeteria Menu'),
        ('EVENT', 'Events'),
    ]
    calendar_type = models.CharField(max_length=5, choices=CALENDAR_TYPES, default='CLASS')
    start_week = models.DateField(null=True, blank=True)
    end_week = models.DateField(null=True, blank=True)
    class Meta:
        verbose_name_plural = 'Calendars'

    def __str__(self):
        return self.title
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not self.timeslots.exists():
            if self.calendar_type == 'CLASS':
                days = TimeSlot.DAY_CHOICES[1:6]  # Sunday to Thursday
                time_ranges = TimeSlot.TIME_RANGES[1:5] + TimeSlot.TIME_RANGES[6:9]            
            elif self.calendar_type == 'CAFE':
                days = TimeSlot.DAY_CHOICES[1:6]  # Sunday to Thursday
                time_ranges = [('12:00 - 1:00', '12:00 - 1:00')]  # 12:00 to 1:00
            else:  # 'EVENT'
                days = TimeSlot.DAY_CHOICES  # All days
                time_ranges = TimeSlot.TIME_RANGES  # All time ranges

            for day in days:
                for time_range in time_ranges:
                    TimeSlot.objects.create(day=day[0], time_range=time_range[0], calendar=self)


LEVEL_CHOICES = [
    ('P1', 'Preparatory 1 / السنة التحضيرية الأولى'),
    ('P2', 'Preparatory 2 / السنة التحضيرية الثانية'),
    ('E1', 'Elementary 1 / السنة الأولى ابتدائي'),
    ('E2', 'Elementary 2 / السنة الثانية ابتدائي'),
    ('E3', 'Elementary 3 / السنة الثالثة ابتدائي'),
    ('E4', 'Elementary 4 / السنة الرابعة ابتدائي'),
    ('E5', 'Elementary 5 / السنة الخامسة ابتدائي'),
    ('M1', 'Middle 1 / السنة الأولى متوسط'),
    ('M2', 'Middle 2 / السنة الثانية متوسط'),
    ('M3', 'Middle 3 / السنة الثالثة متوسط'),
    ('M4', 'Middle 4 / السنة الرابعة متوسط'),
    ('STEM1', 'STEM 1st Year / جذع مشترك علوم و تكنولوجيا'),
    ('LP1', 'Literature and Philosophy 1st Year / جذع مشترك آداب وفلسفة'),
    ('S2', 'Science 2nd Year / السنة الثانية علمي'),
    ('S3', 'Science 3rd Year / السنة الثالثة علمي'),
    ('LP2', 'Literature and Philosophy 2nd Year / السنة الثانية آداب وفلسفة'),
    ('LP3', 'Literature and Philosophy 3rd Year / السنة الثالثة آداب وفلسفة'),
    ('MTH2', 'Mathematics 2nd Year / السنة الثانية رياضيات'),
    ('MTH3', 'Mathematics 3rd Year / السنة الثالثة رياضيات'),
    ('TM2', 'Technical Mathematics 2nd Year / السنة الثانية تقني رياضي'),
    ('TM3', 'Technical Mathematics 3rd Year / السنة الثالثة تقني رياضي'),
    ('FL2', 'Foreign Languages 2nd Year / السنة الثانية لغات أجنبية'),
    ('FL3', 'Foreign Languages 3rd Year / السنة الثالثة لغات أجنبية')
]



    
class Classroom(models.Model):
    name = models.CharField(max_length=255)


    
    level = models.CharField(max_length=5, choices=LEVEL_CHOICES)
    
    teachers=models.ManyToManyField(Teacher, related_name='classrooms', blank=True)

    school_year=models.CharField(max_length=9,null=True)
    subjects = models.ManyToManyField(Subject, related_name='classrooms', blank=True)
    calendar = models.ForeignKey(Calendars, on_delete=models.CASCADE, related_name='calendar', null=True, blank=True)


    def __str__(self):
        return self.name
    


def limit_to_students():
    return {'user_type': 'student'}

class Grade(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE, related_name='grades')
    student = models.ForeignKey(Student, on_delete=models.CASCADE, related_name='student_grades',null=True)
    trimester= models.IntegerField(choices=TRIMESTER_CHOICES, null=True)
    grade = models.IntegerField(null=True,)
    GRADE_TYPE_CHOICES = [('Continous','Continous'),('Test','Test'),('Exam','Exam')]
    GRADE_TYPE_WEIGHTS = {'Continous': 1/4, 'Test': 1/4, 'Exam': 2/4}
    grade_type = models.CharField(max_length=30, choices=GRADE_TYPE_CHOICES, default='Continous')

    @property
    def weight(self):
        return self.GRADE_TYPE_WEIGHTS[self.grade_type]

    def clean(self):
        # Check if the subject is part of the student's classroom's subjects
        if self.subject not in self.student.classroom.subjects.all():
            raise ValidationError("The subject is not part of the student's classroom's subjects.")


    def get_trimester_ordinal(self):
        suffix = {1: 'st', 2: 'nd', 3: 'rd'}.get(self.trimester % 10, 'th')
        return str(self.trimester) + suffix

    def __str__(self):
        return f"{self.student} - {self.subject}: {self.grade} "
    
    #overriding save method to prevent duplicate grades
    def save(self, *args, **kwargs):
        self.clean()
        try:
            existing= Grade.objects.get(subject=self.subject, student=self.student, grade_type =self.grade_type, trimester=self.trimester)
            if existing.pk != self.pk:
                self.pk = existing.pk
        except Grade.DoesNotExist:
            pass

core/forms.py
from django import forms
from .models import Courses, Grade, HomeworkAssignment,HomeworkSubmission, Remarks, Student, Subject

class HomeworkAssignmentForm(forms.ModelForm):
    due_date = forms.DateField(input_formats=['%d-%m-%Y', '%Y-%m-%d'])

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(HomeworkAssignmentForm, self).__init__(*args, **kwargs)

    class Meta:
        model = HomeworkAssignment
        fields = '__all__'
        exclude = ['teacher']

    def clean(self):
        cleaned_data = super().clean()
        teacher = self.request.user.teacher
        classroom = cleaned_data.get('classroom')
        subject = cleaned_data.get('subject')

        if classroom not in teacher.classrooms.all():
            self.add_error('classroom', "You do not teach this classroom.")

        if subject not in teacher.subjects.all():
            self.add_error('subject', "You do not teach this subject.")
class HomeworkSubmissionForm(forms.ModelForm):
    class Meta:
        model = HomeworkSubmission
        fields = ['response', 'submission_file']    
class CoursesForm(forms.ModelForm):
    class Meta:
        model = Courses
        fields = '__all__'
        exclude = ['teacher']


class RemarkForm(forms.ModelForm):
    class Meta:
        model = Remarks
        fields = '__all__'
        exclude =['teacher','student']

class StudentSearchForm(forms.Form):
    student = forms.ModelChoiceField(queryset=Student.objects.all())




from django import forms
from .models import Grade
from .models import TRIMESTER_CHOICES 

class GradeForm(forms.ModelForm):
    trimester = forms.ChoiceField(choices=TRIMESTER_CHOICES)

    class Meta:
        model = Grade
        fields = ['grade', 'grade_type', 'trimester']

core/templates/core/about_us.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>El Hikma School - about us</title>
    <link rel="stylesheet" href="{% static 'services.css' %}">
    
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700&display=swap" rel="stylesheet">
 <!-- Added Google Font -->
</head>
<body>
    <div class="navbar-links">
        <a href="{% url 'home' %}"><img src="{% static 'logo-blue-vecto.svg' %}" alt="Logo"></a>
    
        <ul>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'dashboard' %}">MY DASHBOARD</a>
                </li>
                <li><a href=" {% url 'Courses' %} ">COURSES</a></li>

            {% endif %}
            <li>
                <a href="{% url 'about' %}">ABOUT US</a>
            </li>
            <li>
                <a href="{% url 'events' %}"> ANNOUNCEMENTS AND EVENTS</a>
            </li>
            <li>
                <a href="{% url 'services' %}">OUR SERVICES</a>
            </li>
            <li>
                <a href="{% url 'contact' %}">CONTACT</a>
            </li>
            <li >
                <li>
                {% if user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" class="logout-button">LOGOUT</button>
                    </form>
                </li>
                <li>
                 
                {% else %}
                    <a href="{% url 'login' %}">LOGIN</a>
                {% endif %}
                </li>
            </li>
        </ul>
    </div>

    <section>
        <h1 style="text-align: center; margin-top: 50px; font-weight: bold;">Welcome to El Hikma Private School</h1>
        <p style="text-align: center; font-size: 20px; font-weight: bold;">Providing Quality Education from Preparatory to Middle School</p>
        <p style="text-align: center; font-size: 20px; font-style: italic;">Coming Soon: High School</p>
    
        <div style="text-align: center; margin-top: 50px;">
            <img src="{% static 'fin-année.jpg' %}" alt="Placeholder Image" style="max-width: 50%;">
        </div>
    
        <p style="text-align: justify; font-weight: bold;">At El Hikma Private School, we believe in nurturing not only the academic growth of our students but also their character development. Our educational philosophy is centered around creating a supportive and inclusive learning environment where every student
            feels valued and empowered to reach their full potential.</p>
    
        <p style="text-align: justify; font-weight: bold;">With a curriculum designed to foster critical thinking, creativity, and problem-solving skills, we prepare our students for success in an ever-changing world. Our dedicated faculty members are committed to providing personalized attention to
            each student, ensuring that they receive the guidance and support they need to thrive academically and personally.</p>
    
        <div style="text-align: center; margin-top: 50px;">
            <img src="{% static 'mouloud.jpg' %}" alt="Placeholder Image" style="max-width: 50%;">
        </div>
        <p style="text-align: justify; font-weight: bold;">As we expand our offerings to include high school education, we remain steadfast in our commitment to excellence. We strive to instill in our students a lifelong love of learning, equipping them with the knowledge, skills, and values necessary
            to become responsible global citizens and leaders of tomorrow.</p>
            
        <div style="text-align: center; margin-top: 50px;">
            <img src="{% static 'salles el-Hikma.jpg' %}" alt="Placeholder Image" style="max-width: 50%;">
        </div>
        
    </section>

    <footer>
        <div class="footer-container">
            <div class="footer-section">
                <h3>Quick Links</h3>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Admissions</a></li>
                    <li><a href="#">Academics</a></li>
                    <li><a href="#">Student Life</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="footer-section">
                <h3>Follow Us</h3>
                <p>Stay connected with us on social media:</p>
                <ul>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Instagram</a></li>
                    <li><a href="#">LinkedIn</a></li>
                </ul>
            </div>
            <div class="footer-section">
                <h3>School Hours</h3>
                <p>Sunday to Thursday: 8:00 AM - 4:00 PM</p>
                <p>Saturday and Friday: Closed</p>
            </div>
            <div class="footer-section">
                <h3>Mission Statement</h3>
                <p>"At El Hikma School, we strive to provide a nurturing and challenging environment that fosters academic excellence, character development, and a lifelong love of learning."</p>
            </div>
            <div class="footer-section">
                <h3>Accreditation</h3>
                <p>El Hikma School is accredited by [The Algerian Ministry Of Education].</p>
            </div>
        </div>
        <div class="footer-section legal">
            <p>© 2024 El Hikma School. All rights reserved.</p>
            <p><a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a></p>
        </div>
    </footer>
</body>
</html>

core/templates/core/assign_grades.html
<h2>Assign Grades</h2>
<form method="post">
  {% csrf_token %}
  {{ formset.management_form }}
  {% for form in formset %}
    <div class="grade-form">
      <h3>{{ form.instance.student.user.username }} - {{ form.instance.subject.name }} - {{ form.instance.get_grade_type_display }}</h3>
      Grade: {{ form.grade }}<br>
      Grade Type: {{ form.grade_type }}<br>
      Trimester: {{ form.trimester }}<br>
    </div>
  {% endfor %}
  <button type="submit">Save</button>
</form>

core/templates/core/students_grades.html
{% extends 'core/base.html' %}

{% block content %}
    <h1>Your Grades</h1>
    <table>
        <tr>
            <th>Subject</th>
            <th>Grade</th>
        </tr>
        {% for grade in grades %}
            <tr>
                <td>{% if grade %}
                    {{ grade.subject.name }}
                {% else %}
                    N/A
                {% endif %}</td>
                <td><td>{% if grade %}{{ grade.value }}{% else %}No grade{% endif %}</td></td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

core/templates/core/view_courses.html
{% load static %} 

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>School Courses</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/courses-home.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    
    <style>
        .course-title, .click-info {
            cursor: pointer;
            display: flex;
            align-items: center;
        }
        .arrow {
            margin-right: 10px;
            font-size: 16px;
        }
        .download-container {
            text-align: right;
            margin-top: 10px;
        }
        .download-button {
            background-color: #4CAF50;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            font-size: 16px;
            text-decoration: none;
        }
        .download-button:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <div class="navbar-links">
        <a href="{% url 'home' %}"><img src="{% static 'logo-blue-vecto.svg' %}" alt="Logo"></a>
    
        <ul>
            {% if user.is_authenticated %}
                <li>
                    <a href="{% url 'dashboard' %}">MY DASHBOARD</a>
                </li>
                <li><a href=" {% url 'Courses' %} ">COURSES</a></li>

            {% endif %}
            <li>
                <a href="{% url 'about' %}">ABOUT US</a>
            </li>
            <li>
                <a href="{% url 'events' %}"> ANNOUNCEMENTS AND EVENTS</a>
            </li>
            <li>
                <a href="{% url 'services' %}">OUR SERVICES</a>
            </li>
            <li>
                <a href="{% url 'contact' %}">CONTACT</a>
            </li>
            <li >
                {% if user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit" style="background: transparent; border: none;color: #333;font-size: 20px; font-weight:600;">LOGOUT</button>
                    </form>
                </li>
                <li>
                 
                {% else %}
                    <a href="{% url 'login' %}">LOGIN</a>
                {% endif %}
            </li>
        </ul>
    </div>
    
    
    

    <div class="container">
        <!-- Top Navigation Bar -->
        <div class="top-nav search-form">
            <form method="get">
                <button type="submit" name="search" value="all" class="reset-button">&#x21BA;</button>
                <select name="teacher" class="select-box">
                    <option value="">Teachers</option>
                    {% for teacher in teachers %}
                        <option value="{{ teacher.username }}">{{ teacher.username }}</option>
                    {% endfor %}
                </select>
                <select name="classroom" class="select-box">
                    <option value="">Classrooms</option>
                    {% for classroom in classrooms %}
                        <option value="{{ classroom.name }}">{{ classroom.name }}</option>
                    {% endfor %}
                </select>
                <select name="level" class="select-box">
                    <option value="">Level</option>
                    {% for level in levels %}
                        <option value="{{ level.0 }}">{{ level.1 }}</option>
                    {% endfor %}
                </select>
                <input type="text" name="search" placeholder="Search" class="search">
                <input type="submit" value="Search">
            </form>
        </div>

        <div class="courses">
            <h1>COURSES AND RESOURCES</h1>
            {% for course in courses %}
                <div class="course-box">
                    <h2 class="course-title">
                        <span class="arrow">&#x25B6;</span>
                        Title: {{ course.title }}
                    </h2>
                    <p class="click-info" style="color:#3484cc;">Click to see course details</p>
                    <div class="course-details" style="display: none;">
                        <p><strong>About This Course Resource:</strong> {{ course.description }}</p>
                        <p><strong>Uploaded by:</strong> {{ course.teacher }}</p>
                        <p><strong>Level:</strong> {{ course.get_level_display }}</p>
                        <p><strong>Subject:</strong> {{ course.subject }}</p>
                        <p><strong>Classroom:</strong> {{ course.classroom }}</p>
                        <p><strong>In The Curriculum:</strong> {{ course.is_additional|yesno:"No,Yes" }}</p>
                        <div class="download-container">
                            <a href="{{ course.file.url }}" download class="download-button">Download Course</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>



    <footer>
        <!-- Footer content remains same -->
        <div class="footer-container">
            <div class="footer-section">
                <h3>Quick Links</h3>
                <ul>
                    <li><a href="#">Home</a></li>
                    <li><a href="#">About Us</a></li>
                    <li><a href="#">Admissions</a></li>
                    <li><a href="#">Academics</a></li>
                    <li><a href="#">Student Life</a></li>
                    <li><a href="#">Contact Us</a></li>
                </ul>
            </div>
            <div class="footer-section">
                <h3>Follow Us</h3>
                <p>Stay connected with us on social media:</p>
                <ul>
                    <li><a href="#">Facebook</a></li>
                    <li><a href="#">Twitter</a></li>
                    <li><a href="#">Instagram</a></li>
                    <li><a href="#">LinkedIn</a></li>
                </ul>
            </div>
            <div class="footer-section">
                <h3>School Hours</h3>
                <p>Sunday to Thursday: 8:00 AM - 4:00 PM</p>
                <p>Saturday and Sunday: Closed</p>
            </div>
            <div class="footer-section">
                <h3>Mission Statement</h3>
                <p>"At El Hikma School, we strive to provide a nurturing and challenging environment that fosters academic excellence, character development, and a lifelong love of learning."</p>
            </div>
            <div class="footer-section">
                <h3>Accreditation</h3>
                <p>El Hikma School is accredited by The Algerian Ministry Of Education.</p>
            </div>
            <div class="footer-section legal">
                <p>© 2024 El Hikma School. All rights reserved.</p>
                <p><a href="#">Privacy Policy</a> | <a href="#">Terms of Service</a></p>
            </div>
        </div>
    </footer>
    <script>
        $(document).ready(function(){
            $(".course-title").click(function(){
                var $courseBox = $(this).closest(".course-box");
                var $details = $courseBox.find(".course-details");
                var $clickInfo = $courseBox.find(".click-info");
                var $arrow = $courseBox.find(".arrow");
        
                // Toggle arrow icon immediately
                if ($details.is(":visible")) {
                    $arrow.html("&#x25B6;"); // Change to right arrow
                } else {
                    $arrow.html("&#x25BC;"); // Change to down arrow
                }
        
                // Toggle course details and click info with animation
                $details.slideToggle("fast");
                $clickInfo.slideToggle("fast");
            });
        });
    </script>  


        
        </body>
        </html>